appname: "myapp"
envlabel: "learning"
applabel: "nginx"
maintainerlabel: "helm"
versionlabel: "v2"
replicas: "1"
managedlabel: "deployment"
imgname: "nginx:1.16.0"
imgpullpolicy: "IfNotPresent"
portname: "http"
containerport: "80"
protocol: "TCP"
path: "/"
cpulimit: "2048m"
memorylimit: "16Gi"
cpureq: "512m"
memreq: "4Gi"
portprotocol: "http"